animalapp/urls.py
from django.contrib import admin
from django.urls import path

from animalapp.views import index, create, AnimalCreateView, AnimalDetailView

app_name = 'animalapp'
urlpatterns = [
    path('', index, name='main'),
    path('create/', AnimalCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AnimalDetailView.as_view(), name='detail'),

]

miniproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
import animalapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('animals/', include('animalapp.urls')),

]
if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

animalapp/models.py
from django.db import models

# Create your models here.


SEX_CHOICES = (
            ('Female', 'Female' ),
            ('Male', 'Male' ),

)
class Animal(models.Model):
    sex = models.CharField(max_length=100, blank=False, null=False, choices=SEX_CHOICES)
    image = models.ImageField(upload_to='face/', blank=False, null=False)

animalapp/forms.py
from django.forms import ModelForm
from django import forms
from animalapp.models import Animal


class AnimalCreationForm(ModelForm):
    image = forms.FileField(widget=forms.ClearableFileInput(attrs={"style" :"display:none",
                                                                   "name":"inpFile",
                                                                    "id":"inpFile" }))

    class Meta:
        model = Animal
        fields = '__all__'

animalapp/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, DetailView

from animalapp.forms import AnimalCreationForm
from animalapp.models import Animal


def index(request):
   return render(request,'animalapp/index.html')


def create(request):
   return render(request,'animalapp/create.html')

class AnimalCreateView(CreateView):
   model = Animal
   form_class = AnimalCreationForm
   template_name = 'animalapp/create.html'

   def get_success_url(self):
      return reverse('animalapp:detail', kwargs={'pk': self.object.pk})


class AnimalDetailView(DetailView):
   model = Animal
   context_object_name = 'target_animal'
   template_name = 'animalapp/detail.html'

animalapp/templates/animalapp/create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container m-3 mx-auto">
        <div class="row">
            <div class="col">
                 <form method="POST" action="{% url 'animalapp:create' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                     <div class="button--loading" >
                        <div class="card border-success mb-3" style="max-width: 18rem;">
                          <div class="card-header bg-transparent border-success">
                            <h5 class="card-title text-success text-center">
                                {{ form.sex.label }}
                            </h5>

                            <div class="text-center">
                                {{ form.sex }}
                            </div>
                          </div>
                          <div class="card-body text-success text-center" >
                                <h5 class="card-title" id="preview_text">Add your image</h5>
                                <label class="image-preview spinner-postion" id="imagePreview">
                                    <img src="{% static 'image/face.jpg' %}"
                                         alt="Image Preview"
                                         class="image-preview__image"
                                         style="width: 100%;">
                                    {{ form.image }}
                                </label>
    {#                            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>#}
                          </div>
                          <div class="card-footer bg-transparent border-success text-center">
                              <input class="btn btn-outline-success" id="btnFEtch" type="submit" value="Go!">
                          </div>
                        </div>
                     </div>

                 </form>
            </div>
        </div>
    </div>

{#<div class="spinner-border" role="status">#}
{#  <span class="visually-hidden">Loading...</span>#}
{#</div>#}

    <script>
        const inpFile = document.getElementById("inpFile");
        const previewContainer = document.getElementById("imagePreview");
        const previewText = document.getElementById("preview_text");
        const previewImage = previewContainer.querySelector(".image-preview__image");


        inpFile.addEventListener("change", function () {
            const file = this.files[0];

            if (file) {
                const reader = new FileReader()

                previewImage.style.display = "block";
                previewText.innerHTML = '';

                reader.addEventListener("load", function() {
                    previewImage.setAttribute("src", this.result);
                });

                reader.readAsDataURL(file);
            } else {
                previewDefaultText.style.display = null;
                previewImage.style.display = null;
            }


        })


    </script>


{% endblock %}

{#            <img src="{% static 'image/face.jpg' %}" alt="">#}
{#                <div>{{ form.image.label }}</div>#}
{#                <input type="image">#}
{#                        {{ form.image}}#}
{#                </input>#}
{##}
{#                <label for="id_image">Image :</label>#}
{#                <input id="id_image" type="image" src="{% static 'image/face.jpg' %}" name="image" maxlength="100" required>#}
{#            </p>#}

animalapp/templates/animalapp/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container m-3 mx-auto">
        <div class="row">
            <div class="col">
                    <div class="card border-success mb-3" style="max-width: 120rem;">
                      <div class="card-header bg-transparent border-success">
                        <h5 class="card-title text-success text-center">
                            {{ form.sex.label }}
                        </h5>

                        <div class="text-center">
                            {{ form.sex }}
                        </div>
                      </div>
                          <div class="card-body text-success text-center">
                                <label>
                                    <img src="{% static 'image/animal.jpg' %}">
                                    {{ form.image }}
                                </label>
                          </div>

                    </div>
            </div>
        </div>
    </div>



{% endblock %}

{#            <img src="{% static 'image/face.jpg' %}" alt="">#}
{#                <div>{{ form.image.label }}</div>#}
{#                <input type="image">#}
{#                        {{ form.image}}#}
{#                </input>#}
{##}
{#                <label for="id_image">Image :</label>#}
{#                <input id="id_image" type="image" src="{% static 'image/face.jpg' %}" name="image" maxlength="100" required>#}
{#            </p>#}

animalapp/templates/animalapp/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% include 'head.html' %}
    {% include 'navbar.html' %}

    {% block content %}

    {% endblock %}

</html>

templates/head.html
{% load static %}

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Creative - Start Bootstrap Theme</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Bootstrap Icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
    <!-- SimpleLightbox plugin CSS-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>

templates/navbar.html
<!-- Navigation-->
   {% url 'animalapp:create' as create %}
   {% url 'animalapp:main' as main %}

    {% if request.path == main %}
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">

    {% else %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark  py-3" id="mainNav">

    {% endif %}
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="{% url 'animalapp:main' %}">What Animal Am I?</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto my-2 my-lg-0">
                    <li class="nav-item"><a class="nav-link" href="#about">About</a></li>
                    <li class="nav-item"><a class="nav-link" href="#services">Project Process</a></li>
                    <li class="nav-item"><a class="nav-link" href="#portfolio">Portfolio</a></li>
                    <li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>